development:
  adapter: postgresql
  encoding: utf8
  database: checklist_app_development
  pool: 5
  username: dbuser
  password: pchecklist4)

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: checklist_app_test
  pool: 5
  username: dbuser
  password: pchecklist4)

production:
  adapter: postgresql
  encoding: utf8
  database: checklist_app_production
  pool: 5
  username: dbuser
  password: pchecklist4)